//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducareApplication.EducareService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionTable
    {
        public long STU_ID { get; set; }
        public string STU_NAME { get; set; }
        public string STU_F_NAME { get; set; }
        public string STU_PAR_ADD { get; set; }
        public string STU_CURR_ADD { get; set; }
        public string STU_CITY { get; set; }
        public string STU_STATE { get; set; }
        public string STU_COUNTRY { get; set; }
        public string STU_NATI { get; set; }
        public string STU_GENDER { get; set; }
        public string STU_QUAL { get; set; }
        public string STU_COURSE { get; set; }
        public string STU_PHOTO { get; set; }
        public string STU_MOBILE { get; set; }
        public string STU_DOB { get; set; }
        public string STU_DOA { get; set; }
        public string STU_HOB { get; set; }
        public string STU_HPASS_Y { get; set; }
        public string STU_HPER { get; set; }
        public string STU_HUNI { get; set; }
        public string STU_HROLL { get; set; }
        public string STU_IPASS_Y { get; set; }
        public string STU_IPER { get; set; }
        public string STU_IUNI { get; set; }
        public string STU_IROLL { get; set; }
        public string ImgURL { get; set; }
    }
}
