//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducareApplication.EducareService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTable
    {
        public long COURSE_ID { get; set; }
        public string s_c_id { get; set; }
        public string COURSE_NAME { get; set; }
        public string COURSE_FEES { get; set; }
    }
}
