//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducareApplication.EducareService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeesTable
    {
        public long FEES_ID { get; set; }
        public string FEES_ST_ID { get; set; }
        public string FEES_AMOUNT { get; set; }
        public string FEES_DATE { get; set; }
    }
}
